# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: nuget
    directory: "/src/Avalonia.Samples/"
    exclude-paths:
      - "*.csproj"
    schedule:
      interval: "daily"
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names
      Avalonia:
        # Define patterns to include dependencies in the group (based on
        # dependency name)
        applies-to: version-updates # Applies the group rule to version updates
        patterns:
          - "Avalonia*"  # A wildcard string that matches multiple dependency names
